# deploy-Peter.yml 20250818 1716

# GitHub Actions workflow 的名稱
name: Deploy to Google Cloud Run

# 設定觸發條件
on:
  push:
    branches:
      - main
    paths:
      - 'deployment/Peter/**' # 只在 deployment/Peter 目錄下的檔案有變動時觸發
      - '.github/workflows/deploy-Peter.yml' 

# 設定環境變數
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: gae252-g1-cloud-run-peter
  REGION: asia-east1
  # --- 資料庫環境變數 ---
  CHANNEL_ACCESS_TOKEN:  ${{ secrets.CHANNEL_ACCESS_TOKEN }}
  CHANNEL_SECRET: ${{ secrets.CHANNEL_SECRET }}
  LIFF_ID: ${{ secrets.LIFF_ID }}
  MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  BASE_URL: ${{ secrets.BASE_URL }}
  PLACES_NEARBY_SEARCH_RADIUS: ${{ secrets.PLACES_NEARBY_SEARCH_RADIUS }}
  PLACES_NEARBY_SEARCH_MAX_RESULTS: ${{ secrets.PLACES_NEARBY_SEARCH_MAX_RESULTS }}
  PLACES_NEARBY_PRIMARY_TYPES: ${{ secrets.PLACES_NEARBY_PRIMARY_TYPES }}
  PLACES_NEARBY_RANK_PREFERENCE: ${{ secrets.PLACES_NEARBY_RANK_PREFERENCE }}
  PLACES_TEXT_SEARCH_RADIUS_BIAS: ${{ secrets.PLACES_TEXT_SEARCH_RADIUS_BIAS }}
  PLACES_TEXT_SEARCH_MAX_RESULTS: ${{ secrets.PLACES_TEXT_SEARCH_MAX_RESULTS }}

# 定義工作
jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    # 執行的步驟
    steps:
      # 步驟 1: 從倉庫中拉取最新的程式碼
      - name: Checkout code
        uses: actions/checkout@v4

      # 步驟 2: 使用我們設定的 Secret 登入 Google Cloud
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # 步驟 3: 建置並部署到 Cloud Run
      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          # 告訴 Cloud Run 從 deployment/Peter 目錄下的 Dockerfile 建置
          source: 'deployment/Peter'
          # 將環境變數傳遞給 Cloud Run 服務
          env_vars: |
            CHANNEL_ACCESS_TOKEN=${{ env.CHANNEL_ACCESS_TOKEN }}
            CHANNEL_SECRET=${{ env.CHANNEL_SECRET }}
            LIFF_ID=${{ env.LIFF_ID }}
            MAPS_API_KEY=${{ env.MAPS_API_KEY }}
            DATABASE_URL=${{ env.DATABASE_URL }}
            BASE_URL=${{ env.BASE_URL }}
            PLACES_NEARBY_SEARCH_RADIUS=${{ env.PLACES_NEARBY_SEARCH_RADIUS }}
            PLACES_NEARBY_SEARCH_MAX_RESULTS=${{ env.PLACES_NEARBY_SEARCH_MAX_RESULTS }}
            PLACES_NEARBY_PRIMARY_TYPES=${{ env.PLACES_NEARBY_PRIMARY_TYPES }}
            PLACES_NEARBY_RANK_PREFERENCE=${{ env.PLACES_NEARBY_RANK_PREFERENCE }}
            PLACES_TEXT_SEARCH_RADIUS_BIAS=${{ env.PLACES_TEXT_SEARCH_RADIUS_BIAS }}
            PLACES_TEXT_SEARCH_MAX_RESULTS=${{ env.PLACES_TEXT_SEARCH_MAX_RESULTS }}

