# deploy-Slash.yml 20250807 1546 (v4 - Separated Build and Deploy steps)

name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'deployment/Slash/**'
      - '.github/workflows/deploy-Slash.yml'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: gae252-g1-cloud-run-slash
  REGION: asia-east1
  DB_TYPE: 'MYSQL'
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  # 定義映像檔的名稱和位置
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # [新步驟] 步驟 1: 使用 gcloud builds 進行建置，並停用快取
      - name: Build and Push Docker image
        run: |-
          gcloud builds submit --tag "${{ env.IMAGE_NAME }}" --no-cache "deployment/Slash"

      # [修改後步驟] 步驟 2: 部署上一步驟建置好的映像檔
      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          # 不再使用 'source'，而是直接指定 'image'
          image: "${{ env.IMAGE_NAME }}"
          env_vars: |
            DB_TYPE=${{ env.DB_TYPE }}
            DB_HOST=${{ env.DB_HOST }}
            DB_USER=${{ env.DB_USER }}
            DB_PASSWORD=${{ env.DB_PASSWORD }}
            DB_DATABASE=${{ env.DB_DATABASE }}